rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx-2
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
notifications:
  email:
    recipients:
      - kim@burgestrand.se
    on_success: never
    on_failure: change
