require 'spotify/functions/album'
require 'spotify/functions/album_browse'
require 'spotify/functions/artist'
require 'spotify/functions/artist_browse'
require 'spotify/functions/error'
require 'spotify/functions/image'
require 'spotify/functions/inbox'
require 'spotify/functions/link'
require 'spotify/functions/playlist'
require 'spotify/functions/playlist_container'
require 'spotify/functions/search'
require 'spotify/functions/session'
require 'spotify/functions/toplist_browse'
require 'spotify/functions/track'
require 'spotify/functions/user'

require 'spotify/functions/error_wrapped'
