require 'spotify/type_safety'
require 'spotify/managed_pointer'

require 'spotify/objects/album'
require 'spotify/objects/album_browse'
require 'spotify/objects/artist'
require 'spotify/objects/artist_browse'
require 'spotify/objects/image'
require 'spotify/objects/inbox'
require 'spotify/objects/link'
require 'spotify/objects/playlist'
require 'spotify/objects/playlist_container'
require 'spotify/objects/search'
require 'spotify/objects/session'
require 'spotify/objects/toplist_browse'
require 'spotify/objects/track'
require 'spotify/objects/user'
